apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: {{ .Values.app.name }}
  name: {{ .Values.clusterRoleBinding.name }}-update
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}-update
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}-update
    namespace: {{ .Values.namespace.name }}